views.view.group_manage_members:
  expected_config:
    display:
      default:
        display_options:
          fields:
            rendered_entity:
              admin_label: ''
              alter:
                absolute: false
                alt: ''
                alter_text: false
                ellipsis: true
                external: false
                html: false
                link_class: ''
                make_link: false
                max_length: 0
                more_link: false
                more_link_path: ''
                more_link_text: ''
                nl2br: false
                path: ''
                path_case: none
                prefix: ''
                preserve_tags: ''
                rel: ''
                replace_spaces: false
                strip_tags: false
                suffix: ''
                target: ''
                text: ''
                trim: false
                trim_whitespace: false
                word_boundary: true
              element_class: ''
              element_default_classes: true
              element_label_class: ''
              element_label_colon: true
              element_label_type: ''
              element_type: ''
              element_wrapper_class: ''
              element_wrapper_type: ''
              empty: ''
              empty_zero: false
              entity_type: profile
              exclude: false
              field: rendered_entity
              group_type: group
              hide_alter_empty: true
              hide_empty: false
              id: rendered_entity
              label: Member
              plugin_id: rendered_entity
              relationship: profile
              table: profile
              view_mode: table
  update_actions:
    delete:
      display:
        default:
          display_options:
            fields:
              rendered_entity:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_type: profile
                exclude: false
                field: rendered_entity
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: rendered_entity
                label: Member
                plugin_id: rendered_entity
                relationship: profile
                table: profile
                view_mode: table
    change:
      display:
        default:
          display_options:
            fields:
              profile_entity_sortable:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_type: profile
                exclude: false
                field: profile_entity_sortable
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: profile_entity_sortable
                label: Member
                plugin_id: profile_entity_sortable
                relationship: profile
                table: profile
                view_mode: table
