core.entity_view_display.comment.comment.activity_comment:
  expected_config:
    content:
      field_comment_body:
        settings:
          trim_length: 300
        type: text_trimmed
      like_and_dislike:
        weight: 2
      links:
        region: content
        settings: { }
        third_party_settings: { }
        weight: 1
  update_actions:
    delete:
      content:
        links:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 1
    add:
      hidden:
        field_comment_anonymously: true
        field_comment_files: true
        langcode: true
        private_message_link: true
        links: true
    change:
      content:
        field_comment_body:
          settings:
            more_class: more-link
            more_link: true
            more_text: more
            summary_handler: full
            trim_length: 250
            trim_options:
              text: false
              trim_zero: false
            trim_suffix: ...
            trim_type: chars
            wrap_class: trimmed
            wrap_output: false
          type: smart_trim
