core.entity_view_display.group.closed_group.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        langcode: true
        social_tagging: true
core.entity_view_display.group.flexible_group.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        langcode: true
        social_tagging: true
core.entity_view_display.group.open_group.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        langcode: true
        social_tagging: true
core.entity_view_display.group.public_group.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        langcode: true
        social_tagging: true
core.entity_view_display.node.event.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      content:
        groups_type_cc:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_challenge:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_secret_group:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
      hidden:
        field_event_an_enroll: true
        field_event_managers: true
        field_event_max_enroll: true
        field_event_max_enroll_num: true
        field_event_type: true
        langcode: true
        shariff_field: true
        social_tagging: true
core.entity_view_display.node.landing_page.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      content:
        groups_type_cc:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_challenge:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_secret_group:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
      hidden:
        langcode: true
        private_message_link: true
        shariff_field: true
        social_tagging: true
core.entity_view_display.node.page.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      content:
        groups_type_cc:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_challenge:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_secret_group:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
      hidden:
        langcode: true
        private_message_link: true
        shariff_field: true
        social_tagging: true
core.entity_view_display.node.topic.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      content:
        groups_type_cc:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_challenge:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
        groups_type_secret_group:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: -5
      hidden:
        field_exclude_from_library: true
        langcode: true
        private_message_link: true
        shariff_field: true
        social_tagging: true
core.entity_view_display.paragraph.featured.preview:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_featured_layout: true
core.entity_view_display.profile.profile.wide_teaser:
  expected_config: {  }
  update_actions:
    add:
      content:
        badges:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 0
      hidden:
        field_birthdate: true
        field_birthdate_next: true
        field_profile_nick_name: true
        field_profile_organization_tag: true
field.field.paragraph.featured.field_featured_items:
  expected_config: {  }
  update_actions:
    add:
      settings:
        path_alias:
          handler: 'default:path_alias'
          handler_settings: {  }
