block.block.socialblue_profile_statistic_block:
  expected_config:
    visibility:
      request_path:
        pages: "/user\r\n/user/*/stream\r\n/user/*/events\r\n/user/*/topics\r\n/user/*/groups\r\n/user/*/information\r\n/user/*/discussions\r\n/user/*/ideas\r\n/user/*/challenges"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/user\r\n/user/*/stream\r\n/user/*/events\r\n/user/*/topics\r\n/user/*/groups\r\n/user/*/information\r\n/user/*/discussions\r\n/user/*/ideas\r\n/user/*/challenges\r\n/user/*/courses"
