core.entity_form_display.node.event.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_enroll_method:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 122
        field_event_enroll_outside_group:
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
          type: boolean_checkbox
          weight: 123
      third_party_settings:
        field_group:
          group_enrollment:
            children:
              - group_enrollment_methods
          group_enrollment_methods:
            children:
              - field_enroll_method
              - field_event_enroll_outside_group
            format_settings:
              attributes: ''
              classes: enrollment-methods
              effect: none
              element: div
              id: ''
              label: 'Enrollment options fieldset'
              label_element: h3
              required_fields: false
              show_label: false
              speed: fast
            format_type: html_element
            label: 'Enrollment options fieldset'
            parent_name: group_enrollment
            region: hidden
            weight: 20
core.entity_view_display.node.event.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_enroll_method: true
        field_event_enroll_outside_group: true
field.storage.node.field_enroll_method:
  expected_config:
    settings:
      allowed_values:
        -1:
          label: 'Enroll directly - users can enroll in this event without approval'
        0:
          label: 'Request to enroll - user enrollment requests need to be approved by event organisers'
  update_actions:
    add:
      settings:
        allowed_values:
          -
            label: 'Invite-only - users can only be added or invited by event organisers'
            value: 3
    change:
      settings:
        allowed_values:
          -1:
            label: 'Open for all - users can enroll in this event without approval'
          0:
            label: 'Open to requests - user requests to enroll need to be approved by event organisers'