field.storage.node.field_enroll_method:
  expected_config:
    settings:
      allowed_values:
        -1:
          label: 'Open to enroll - users can enroll for this event without approval'
        0:
          label: 'Request to enroll - users can "request to enroll" for this event which event organisers approve/decline'
        1:
          label: 'Invite-only - users can only enroll for this event if they are added/invited by event organisers'
  update_actions:
    change:
      settings:
        allowed_values:
          -1:
            label: 'Open to enroll - users can enrol for this event without approval'
          0:
            label: 'Request to enroll - users can ''request to enroll'' for this event which event organisers approve/decline'
          1:
            label: 'Invite-only - users can only enrol for this event if they are added/invited by event organisers'
