social_views_infinite_scroll.settings:
  type: config_object
  label: 'Social views infinite scroll settings'
  mapping:
    views_list:
      type: sequence
      label: 'Enable scroll for this view'
      sequence:
        type: string
    button_text:
      type: string
      label: 'Button text'
    automatically_load_content:
      type: boolean
      label: 'Automatically Load Content'
