core.entity_form_display.block_content.basic.default:
  expected_config:
    content:
      field_basic_link:
        weight: 2
      field_text_block:
        weight: 1
  update_actions:
    change:
      content:
        field_basic_link:
          weight: 1
        field_text_block:
          weight: 0
core.entity_view_display.block_content.basic.default:
  expected_config:
    content:
      field_basic_link:
        settings:
          rel: '0'
          target: '0'
        weight: 2
      field_text_block:
        weight: 1
  update_actions:
    change:
      content:
        field_basic_link:
          settings:
            rel: ''
            target: ''
          weight: 1
        field_text_block:
          weight: 0
field.field.block_content.basic.field_basic_link:
  expected_config:
    translatable: true
  update_actions:
    change:
      translatable: false
