# Schema for the configuration files of the Social Content Moderation module.

social_content_moderation.settings:
  type: config_object
  label: 'Social Content Moderation settings'
  mapping:
    mandatory_reason:
      type: boolean
      label: 'Mandatory reason when reporting inappropriate content'
    unpublish_immediately:
      type: boolean
      label: 'Reported inappropriate content is unpublished immediately'
