social_comment.comment_settings:
  type: config_object
  label: 'Social Comment Settings'
  mapping:
    redirect_comment_to_entity:
      type: boolean
      label: 'Redirect a comment view to its parent entity'
    remove_author_field:
      type: boolean
      label: 'Remove author field from comment form'
    wysiwyg:
      type: boolean
      label: 'Authenticated users are allowed to use WYSIWYG editor in comment form'
