social_swiftmail.settings:
  type: config_object
  label: 'Social Swiftmail Settings'
  mapping:
    remove_open_social_branding:
      type: boolean
      label: 'Open Social Branding will be replaced by site name (and slogan if available).'
    template_header:
      type: string
      label: 'Notification email header'
    template_header_format:
      type: string
      label: 'Text format for the notification email header'
    template_footer:
      type: string
      label: 'Notification email footer'
    template_footer_format:
      type: string
      label: 'Text format for the notification email footer'
