core.entity_form_display.group.flexible_group.default:
  expected_config:
    content:
      path:
        weight: 3
    third_party_settings:
      field_group:
        group_content:
          weight: 1
        group_location:
          weight: 2
  update_actions:
    add:
      content:
        field_members_visibility:
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
          type: boolean_checkbox
          weight: 11
      third_party_settings:
        field_group:
          group_content:
            group_outsider_settings:
              children:
                - field_members_visibility
              format_settings:
                classes: ''
                description: ''
                id: ''
                required_fields: true
              format_type: fieldset
              label: 'Non-member settings'
              parent_name: ''
              region: content
              weight: 2
    change:
      third_party_settings:
        field_group:
          group_content:
            weight: 4
          group_location:
            weight: 5
          group_outsider_settings:
            children:
              - field_members_visibility
            format_settings:
              classes: ''
              description: ''
              id: ''
              required_fields: true
            format_type: fieldset
            label: 'Non-member settings'
            parent_name: ''
            region: content
            weight: 2
